### ISSUE TITLE
Can I advertise the client?

### ISSUE THREAD

**Issue by Tri125** [Zhouzi/gwent-api-client#1]
Do you mind if I link/advertise the client on the API website https://gwentapi.com and possibly in the doc of the project?

**Comment by zhouzi** [comment]
That would actually be much appreciated 👍

**Comment by zhouzi** [comment]
Oh and by the way, I created [awesome-gwent](https://github.com/Zhouzi/awesome-gwent) and list GwentAPI in the [developer tools](https://github.com/Zhouzi/awesome-gwent#developer-tools) section. I hope you don't mind 😄 

And feel free to submit an issue there if you have any resources to share.

**Comment by Tri125** [comment]
Consider it done.
