### ISSUE TITLE
Easy way to polyfill fetch and use this in Node?

### ISSUE THREAD

**Issue by Soreine** [Zhouzi/gwent-api-client#2]
This lib relies on `window.fetch`, which does not exist in Node. Here is what I did in a node script, in order to make it work. Is it the best approach?

```
const fetch = require('node-fetch');
// Polyfill for GwentAPI
global.fetch = fetch;

const GwentAPI = require('gwent-api-client').default;

// Use GwentAPI
```

**Comment by zhouzi** [comment]
I just released 1.1.0 with isomorphic-fetch, which means it now works with NodeJS out of the box 🎉
