### ISSUE TITLE
Support the lang option for Cards

### ISSUE THREAD

**Issue by Tri125** [Zhouzi/gwent-api-client#3]
The option is available since v0.6 of the API.
Documentation here: https://gwentapi.com/swagger/index.html#operation--v0-cards-get
It's available on the Card resources but doesn't really matter for ``/v0/cards/{cardID}/variations`` because there's nothing getting localized for variations.

**Comment by zhouzi** [comment]
Thanks for the heads-up @Tri125, I will add it as well as "name" (search) and support for the "If-Modified-Since" header 👍  I'll release a new version later today.

**Comment by zhouzi** [comment]
I updated the documentation. Since the calls to `.<resource>.list()` are just passing through the request parameters, it's now referencing the API documentation.

I opened a separate issue to add support for the If-Modified-Since header #4
